# Generated by Django 5.2.5 on 2025-08-26 01:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('formatted_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
