# Generated by Django 5.2.5 on 2025-08-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_document_line_count_document_paragraph_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='syllable_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
